version: '2'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - '80:80'
      - '443:443'
    environment:
      VIRTUAL_HOST: cred-auth-manager.com
    depends_on:
      - app
    links:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    expose:
      - 3000
    environment:
      NODE_ENV: development
      DATABASE: postgres://db-user:password@db:5432/cred-auth-manager
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/opt/cred-auth-manager
      - /opt/cred-auth-manager/node_modules
  db:
    restart: always
    image: postgres:9.6
    expose:
      - 5432
    environment:
      # The following environment vars will be automatically picked up by the
      # docker image and used to initialize the database.
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cred-auth-manager
