version: '2'
services:
  app:
    environment:
      NODE_ENV: production
      DATABASE: postgres://POSTGRES_USER:POSTGRES_PASSWORD@db:5432/cred-auth-manager
  db:
    environment:
      # Environment variables to configure Postgres on startup.
      # Environment variables with only a key are resolved to their values on
      # the machine Compose is running on. We do this to prevent ourselves
      # from committing sensitive data to the repo.
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=cred-auth-manager
