version: '3.1'

services:
  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./server:/opt/app/server
    links:
      - db
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE=postgres://postgres:dbpass@db:5432/cred-auth-manager

  admin:
    build:
      context: .
      dockerfile: Dockerfile-admin
    ports:
      - 8000:80
      - 8443:443
    depends_on:
      - server

  db:
    image: postgres:9.5.6
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cred-auth-manager
      - POSTGRES_PASSWORD=dbpass
