version: '2'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - '80:80'
      - '443:443'
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: cred-auth-manager.com
    links:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE: postgres://db-user:password@db:5432/cred-auth-manager
    links:
      - db
    volumes:
      - .:/opt/cred-auth-manager
      - /opt/cred-auth-manager/node_modules
  db:
    restart: always
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      # The following environment vars will be automatically picked up by the
      # docker image and used to initialize the database.
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: password
